import Head from 'next/head'
import { useRouter } from "next/router";
import axios from "axios";
import { useState, useEffect } from "react";
import SideNave from "../components/SideNave";
import ProfileBar from "../components/ProfileBar";
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faPlus, faXmark } from '@fortawesome/free-solid-svg-icons'
import useSWR, { mutate } from "swr";

const URL = `http://localhost:3333/api`;
const fetcher = (url) => axios.get(`${URL}/allUser`).then((res) => res.data);

export default function Home({ token }) {

  const router = useRouter();
  const { data, error } = useSWR(URL, fetcher);

  const checkSession = async () => {
    if (!token)
      router.push('/login');
  }

  useEffect(() => {
    checkSession();
  }, [])



  // useEffect(() => {
  //   console.log(data);
  // }, [])

  return (
    <>
      <Head>
        <title>Dashboard - Residences Sindhorn Kempinski</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SideNave />
      {token ? <ProfileBar token={token} /> : <></>}


      <div className="md:pl-[340px] w-full  h-full bg-[#f0f1f6] p-10 flex justify-center">
        <div className="bg-white  h-full w-full shadow rounded-lg p-10  flex flex-col items-center">
          <div className="w-full flex justify-between mb-4">
            <div className="h-full flex items-center gap-3">
              <p className="mr-5 font-semibold">Filter</p>
              <label>
                <input type="checkbox" className="accent-pink-500" /> Interior
              </label>
              <label>
                <input type="checkbox" className="accent-pink-500" /> Exterior
              </label>
              <label>
                <input type="checkbox" className="accent-pink-500" /> Video
              </label>
            </div>
            <button className="w-fit px-4 py-2 bg-green-400 text-white rounded font-semibold flex items-center"> <FontAwesomeIcon icon={faPlus} className="h-5 w-5 mr-2" />New Picture</button>
          </div>

          <div className="w-full grid grid-cols-4 gap-3">
            <div className="w-full h-60 bg-black relative">
              <div className="absolute top-2 right-2 w-10 h-10 bg-red-600 rounded-full flex justify-center items-center">
                <FontAwesomeIcon icon={faXmark} className="h-7 w-7 text-white" />
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="md:pl-[340px] w-full min-h-screen h-full bg-[#f0f1f6] p-10 flex justify-center">
        <div className="bg-white  h-full w-full shadow rounded-lg p-10  flex flex-col items-center">
          <div className="w-full flex justify-between mb-4">
            <div className="h-full flex items-center gap-3">
              <p className="mr-5 font-semibold text-xl">Member List</p>
            </div>

          </div>
          {data ? <div> {data.map((item, index) => (
            <div key={index} className="w-full flex ">
              <p className="px-5">  {item.username} </p>
              <p className="px-5">
                {item.fName}
              </p>
              <p className="px-5">

                {item.lName}
              </p>
            </div>
          ))} </div> : <div>Waiting</div>

          }


        </div>
      </div>

    </>
  )
}

export function getServerSideProps({ req, res }) {
  return { props: { token: req.cookies.token || "" } };
}